version: '3.7'

services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - blablabla
    depends_on:
      - mysql_db
  mysql_db:
    image: "mysql:8.0"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mobilefarm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 12345
    networks:
      - blablabla

volumes:
  db:
networks:
  blablabla: